name: pre-commit

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/pre-commit.yaml"
      - "pre_commit.js"
      - "common/version.sh"
  schedule:
    # daily on github default branch
    - cron: "0 1/15 * * *"

jobs:
  main:
    strategy:
      matrix:
        repo:
          - { repo: Trim21/BGmi, branch: dev }
          - { repo: Trim21/pol, branch: master }
          - { repo: Trim21/transmission-rpc, branch: dev }
    #      - { repo: BGmi/BGmi-NG, branch: feature/core }

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      ################ node

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - run: npm ci

      ################ end node

      ################ python

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Get Latest tools version
        id: get-version
        run: bash ./common/version.sh

      - uses: Trim21/setup-poetry@v1

      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo.repo }}
          ref: ${{ matrix.repo.branch }}
          path: ${{ matrix.repo.repo }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Fetch All Branches
        working-directory: ./${{ matrix.repo.repo }}
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - uses: actions/cache@v2
        name: Cache Python Packages
        with:
          path: ~/.local
          key: poetry-${{ matrix.repo.repo }}-${{ steps.get-version.outputs.PY }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ matrix.repo.repo }}-${{ steps.get-version.outputs.PY }}-

      - uses: actions/cache@v2
        name: Cache Pre-Commit
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ matrix.repo.repo }}-${{ steps.get-version.outputs.PY }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ matrix.repo.repo }}-${{ steps.get-version.outputs.PY }}-

      - name: Install Dependencies
        working-directory: ./${{ matrix.repo.repo }}
        run: pip install --user --no-deps -r <(poetry export -f requirements.txt --dev)

      - name: check if pre-commit update
        run: node $GITHUB_WORKSPACE/pre_commit.js
        working-directory: ./${{ matrix.repo.repo }}
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          REPO: ${{ matrix.repo.repo }}
          BRANCH: ${{ matrix.repo.branch }}
